#!/bin/sh

echo "Download the latest Apple Developer Tools and install for compiling stuff ..."
echo "Hit enter to continue..."
read     # this should pause and wait for user to do the manual install

# Not sure if this is needed anymore with Xcode 4.4+
# sudo /usr/bin/xcode-select -switch /Applications/Xcode.app/Contents/Developer

# echo "Checking for SSH key, generating one if it doesn't exist ..."
#   [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

# echo "Copying public key to clipboard. Paste it into your Github account ..."
#   [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
#   open https://github.com/account/ssh

echo "Installing Homebrew, a good OS X package manager ..."
  ruby <(curl -fsSkL raw.github.com/mxcl/homebrew/go)
  brew update

echo "Put Homebrew location earlier in PATH ..."
  echo "export PATH='/usr/local/bin:$PATH'" >> ~/.bash_profile
  source ~/.bash_profile

echo "Installing GCC 4.2 compiler for legacy (ruby 1.8.7) compatibilty ..."
  brew tap homebrew/dupes
  brew install apple-gcc42

echo "Installing Postgres, a good open source relational database ..."
  brew install postgres --no-python

echo "Installing ack, a good way to search through files ..."
  brew install ack

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install imagemagick

# echo "Installing QT, used by Capybara Webkit for headless Javascript integration testing ..."
#   brew install qt

echo "Download XQuartz from http://xquartz.macosforge.org/landing/ and install..."
  echo "Hit enter to continue..."
  read     # this should pause and wait for user to do the manual install
  echo 'export CPPFLAGS=-I/opt/X11/include' >> ~/.bash_profile

echo "Installing rbenv and ruby-build for managing and installing ruby versions ..."
  brew install rbenv
  brew install ruby-build
  echo 'eval "$(rbenv init -)"' >> ~/.bash_profile

curl -s https://raw.github.com/natebird/laptop/master/ruby | sh
